# fly.toml app configuration file generated for old-glitter-7064 on 2023-08-31T22:24:49+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "old-glitter-7064"
primary_region = "sin"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

    
[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"